// GENERATED: local female-voice files for all 100 animals.
export const ANIMAL_VOICES = {
  "Lion": { en: "/voices/1-lion.mp3", ar: "/voices/1-lion-ar.mp3" },
  "Elephant": { en: "/voices/2-elephant.mp3", ar: "/voices/2-elephant-ar.mp3" },
  "Giraffe": { en: "/voices/3-giraffe.mp3", ar: "/voices/3-giraffe-ar.mp3" },
  "Tiger": { en: "/voices/4-tiger.mp3", ar: "/voices/4-tiger-ar.mp3" },
  "Leopard": { en: "/voices/5-leopard.mp3", ar: "/voices/5-leopard-ar.mp3" },
  "Zebra": { en: "/voices/6-zebra.mp3", ar: "/voices/6-zebra-ar.mp3" },
  "Gorilla": { en: "/voices/7-gorilla.mp3", ar: "/voices/7-gorilla-ar.mp3" },
  "Bear": { en: "/voices/8-bear.mp3", ar: "/voices/8-bear-ar.mp3" },
  "Fox": { en: "/voices/9-fox.mp3", ar: "/voices/9-fox-ar.mp3" },
  "Wolf": { en: "/voices/10-wolf.mp3", ar: "/voices/10-wolf-ar.mp3" },
  "Hippopotamus": { en: "/voices/11-hippopotamus.mp3", ar: "/voices/11-hippopotamus-ar.mp3" },
  "Rhinoceros": { en: "/voices/12-rhinoceros.mp3", ar: "/voices/12-rhinoceros-ar.mp3" },
  "Kangaroo": { en: "/voices/13-kangaroo.mp3", ar: "/voices/13-kangaroo-ar.mp3" },
  "Koala": { en: "/voices/14-koala.mp3", ar: "/voices/14-koala-ar.mp3" },
  "Panda": { en: "/voices/15-panda.mp3", ar: "/voices/15-panda-ar.mp3" },
  "Monkey": { en: "/voices/16-monkey.mp3", ar: "/voices/16-monkey-ar.mp3" },
  "Sloth": { en: "/voices/17-sloth.mp3", ar: "/voices/17-sloth-ar.mp3" },
  "Beaver": { en: "/voices/18-beaver.mp3", ar: "/voices/18-beaver-ar.mp3" },
  "Otter": { en: "/voices/19-otter.mp3", ar: "/voices/19-otter-ar.mp3" },
  "Badger": { en: "/voices/20-badger.mp3", ar: "/voices/20-badger-ar.mp3" },
  "Deer": { en: "/voices/21-deer.mp3", ar: "/voices/21-deer-ar.mp3" },
  "Camel": { en: "/voices/22-camel.mp3", ar: "/voices/22-camel-ar.mp3" },
  "Lizard": { en: "/voices/23-lizard.mp3", ar: "/voices/23-lizard-ar.mp3" },
  "Chipmunk": { en: "/voices/24-chipmunk.mp3", ar: "/voices/24-chipmunk-ar.mp3" },
  "Raccoon": { en: "/voices/25-raccoon.mp3", ar: "/voices/25-raccoon-ar.mp3" },
  "Dolphin": { en: "/voices/26-dolphin.mp3", ar: "/voices/26-dolphin-ar.mp3" },
  "Whale": { en: "/voices/27-whale.mp3", ar: "/voices/27-whale-ar.mp3" },
  "Octopus": { en: "/voices/28-octopus.mp3", ar: "/voices/28-octopus-ar.mp3" },
  "Shark": { en: "/voices/29-shark.mp3", ar: "/voices/29-shark-ar.mp3" },
  "Crab": { en: "/voices/30-crab.mp3", ar: "/voices/30-crab-ar.mp3" },
  "Lobster": { en: "/voices/31-lobster.mp3", ar: "/voices/31-lobster-ar.mp3" },
  "Shrimp": { en: "/voices/32-shrimp.mp3", ar: "/voices/32-shrimp-ar.mp3" },
  "Squid": { en: "/voices/33-squid.mp3", ar: "/voices/33-squid-ar.mp3" },
  "Sea Turtle": { en: "/voices/34-sea-turtle.mp3", ar: "/voices/34-sea-turtle-ar.mp3" },
  "Pufferfish": { en: "/voices/35-pufferfish.mp3", ar: "/voices/35-pufferfish-ar.mp3" },
  "Tropical Fish": { en: "/voices/36-tropical-fish.mp3", ar: "/voices/36-tropical-fish-ar.mp3" },
  "Seal": { en: "/voices/37-seal.mp3", ar: "/voices/37-seal-ar.mp3" },
  "Jellyfish": { en: "/voices/38-jellyfish.mp3", ar: "/voices/38-jellyfish-ar.mp3" },
  "Snail": { en: "/voices/39-snail.mp3", ar: "/voices/39-snail-ar.mp3" },
  "Fish": { en: "/voices/40-fish.mp3", ar: "/voices/40-fish-ar.mp3" },
  "Dugong": { en: "/voices/41-dugong.mp3", ar: "/voices/41-dugong-ar.mp3" },
  "Sea Lion": { en: "/voices/42-sea-lion.mp3", ar: "/voices/42-sea-lion-ar.mp3" },
  "Oyster": { en: "/voices/43-oyster.mp3", ar: "/voices/43-oyster-ar.mp3" },
  "Coral Reef": { en: "/voices/44-coral-reef.mp3", ar: "/voices/44-coral-reef-ar.mp3" },
  "Walrus": { en: "/voices/45-walrus.mp3", ar: "/voices/45-walrus-ar.mp3" },
  "Golden Eagle": { en: "/voices/46-eagle.mp3", ar: "/voices/46-eagle-ar.mp3" },
  "Parrot": { en: "/voices/47-parrot.mp3", ar: "/voices/47-parrot-ar.mp3" },
  "Owl": { en: "/voices/48-owl.mp3", ar: "/voices/48-owl-ar.mp3" },
  "Peacock": { en: "/voices/49-peacock.mp3", ar: "/voices/49-peacock-ar.mp3" },
  "Penguin": { en: "/voices/50-penguin.mp3", ar: "/voices/50-penguin-ar.mp3" },
  "Swan": { en: "/voices/51-swan.mp3", ar: "/voices/51-swan-ar.mp3" },
  "Flamingo": { en: "/voices/52-flamingo.mp3", ar: "/voices/52-flamingo-ar.mp3" },
  "Duck": { en: "/voices/53-duck.mp3", ar: "/voices/53-duck-ar.mp3" },
  "Rooster": { en: "/voices/54-rooster.mp3", ar: "/voices/54-rooster-ar.mp3" },
  "Hen": { en: "/voices/55-hen.mp3", ar: "/voices/55-hen-ar.mp3" },
  "Dove": { en: "/voices/56-dove.mp3", ar: "/voices/56-dove-ar.mp3" },
  "Falcon": { en: "/voices/57-falcon.mp3", ar: "/voices/57-falcon-ar.mp3" },
  "Bluebird": { en: "/voices/58-bluebird.mp3", ar: "/voices/58-bluebird-ar.mp3" },
  "Turkey": { en: "/voices/59-turkey.mp3", ar: "/voices/59-turkey-ar.mp3" },
  "Chic": { en: "/voices/60-chic.mp3", ar: "/voices/60-chic-ar.mp3" },
  "Vulture": { en: "/voices/61-vulture.mp3", ar: "/voices/61-vulture-ar.mp3" },
  "Woodpecker": { en: "/voices/62-woodpecker.mp3", ar: "/voices/62-woodpecker-ar.mp3" },
  "Puffin": { en: "/voices/63-puffin.mp3", ar: "/voices/63-puffin-ar.mp3" },
  "Seagull": { en: "/voices/64-seagull.mp3", ar: "/voices/64-seagull-ar.mp3" },
  "Crow": { en: "/voices/65-crow.mp3", ar: "/voices/65-crow-ar.mp3" },
  "Cow": { en: "/voices/66-cow.mp3", ar: "/voices/66-cow-ar.mp3" },
  "Sheep": { en: "/voices/67-sheep.mp3", ar: "/voices/67-sheep-ar.mp3" },
  "Horse": { en: "/voices/68-horse.mp3", ar: "/voices/68-horse-ar.mp3" },
  "Goat": { en: "/voices/69-goat.mp3", ar: "/voices/69-goat-ar.mp3" },
  "Pig": { en: "/voices/70-pig.mp3", ar: "/voices/70-pig-ar.mp3" },
  "Donkey": { en: "/voices/71-donkey.mp3", ar: "/voices/71-donkey-ar.mp3" },
  "Ox": { en: "/voices/72-ox.mp3", ar: "/voices/72-ox-ar.mp3" },
  "Llama": { en: "/voices/73-llama.mp3", ar: "/voices/73-llama-ar.mp3" },
  "Shepherd Dog": { en: "/voices/74-shepherd-dog.mp3", ar: "/voices/74-shepherd-dog-ar.mp3" },
  "Barn Cat": { en: "/voices/75-barn-cat.mp3", ar: "/voices/75-barn-cat-ar.mp3" },
  "Goose": { en: "/voices/76-goose.mp3", ar: "/voices/76-goose-ar.mp3" },
  "Buffalo": { en: "/voices/77-buffalo.mp3", ar: "/voices/77-buffalo-ar.mp3" },
  "Farm Rabbit": { en: "/voices/78-farm-rabbit.mp3", ar: "/voices/78-farm-rabbit-ar.mp3" },
  "Honeybee": { en: "/voices/79-honeybee.mp3", ar: "/voices/79-honeybee-ar.mp3" },
  "Pony": { en: "/voices/80-pony.mp3", ar: "/voices/80-pony-ar.mp3" },
  "Cat": { en: "/voices/81-cat.mp3", ar: "/voices/81-cat-ar.mp3" },
  "Dog": { en: "/voices/82-dog.mp3", ar: "/voices/82-dog-ar.mp3" },
  "Hamster": { en: "/voices/83-hamster.mp3", ar: "/voices/83-hamster-ar.mp3" },
  "Rabbit": { en: "/voices/84-rabbit.mp3", ar: "/voices/84-rabbit-ar.mp3" },
  "Budgie": { en: "/voices/85-budgie.mp3", ar: "/voices/85-budgie-ar.mp3" },
  "Goldfish": { en: "/voices/86-goldfish.mp3", ar: "/voices/86-goldfish-ar.mp3" },
  "Turtle": { en: "/voices/87-turtle.mp3", ar: "/voices/87-turtle-ar.mp3" },
  "Gecko": { en: "/voices/88-gecko.mp3", ar: "/voices/88-gecko-ar.mp3" },
  "Hedgehog": { en: "/voices/89-hedgehog.mp3", ar: "/voices/89-hedgehog-ar.mp3" },
  "Canary": { en: "/voices/90-canary.mp3", ar: "/voices/90-canary-ar.mp3" },
  "Butterfly": { en: "/voices/91-butterfly.mp3", ar: "/voices/91-butterfly-ar.mp3" },
  "Bee": { en: "/voices/92-bee.mp3", ar: "/voices/92-bee-ar.mp3" },
  "Ladybug": { en: "/voices/93-ladybug.mp3", ar: "/voices/93-ladybug-ar.mp3" },
  "Ant": { en: "/voices/94-ant.mp3", ar: "/voices/94-ant-ar.mp3" },
  "Cricket": { en: "/voices/95-cricket.mp3", ar: "/voices/95-cricket-ar.mp3" },
  "Mosquito": { en: "/voices/96-mosquito.mp3", ar: "/voices/96-mosquito-ar.mp3" },
  "Housefly": { en: "/voices/97-housefly.mp3", ar: "/voices/97-housefly-ar.mp3" },
  "Spider": { en: "/voices/98-spider.mp3", ar: "/voices/98-spider-ar.mp3" },
  "Dragonfly": { en: "/voices/99-dragonfly.mp3", ar: "/voices/99-dragonfly-ar.mp3" },
  "Caterpillar": { en: "/voices/100-caterpillar.mp3", ar: "/voices/100-caterpillar-ar.mp3" },
}
